Dashboard Layout
smswithoutborders/gateway-client-reliability-dashboard pull request #1
Opened 2024-03-21 12:54 UTC by Vanessa-Kris

2024-03-21 14:23 UTC, PromiseFru requested changes
Please see my comments, @Vanessa-Kris.

2024-03-21 14:23 UTC, PromiseFru commented on public/index.html
> +</html>
Update the content, remove irrelevant comments, and ensure the correct content is used.

2024-03-21 14:23 UTC, PromiseFru commented on public/manifest.json
> +}
Update the content of the manifest to ensure that the correct information is included.

2024-03-21 14:23 UTC, PromiseFru commented on src/index.js
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
Remove irrelevant comments

2024-03-21 14:23 UTC, PromiseFru commented on src/logo.svg
Remove irrelevant files

2024-03-21 14:56 UTC, Vanessa-Kris commented
@PromiseFru I've made the required update/changes.

2024-03-21 15:32 UTC, PromiseFru requested changes
Looking good, @Vanessa-Kris! Just a few more minor tweaks. 😉

2024-03-21 15:32 UTC, PromiseFru commented on public/index.html
> +      content="Gateway Clients Resiliance Dashboard"
```suggestion
      content="Gateway Clients Reliability Dashboard"
```

2024-03-21 15:32 UTC, PromiseFru commented on public/index.html
> +    <title>Dashboard</title>
```suggestion
    <title>Gateway Clients Reliability Dashboard</title>
```

2024-03-21 15:32 UTC, PromiseFru commented on public/manifest.json
> +  "name": "Gateway Clients Resiliance Dashboard",
```suggestion
  "short_name": "Reliability Dashboard",
  "name": "Gateway Clients Reliability Dashboard",
```

2024-03-22 13:19 UTC, PromiseFru requested changes

2024-03-22 13:19 UTC, PromiseFru commented on src/App.css
> +
Remove irrelevant comments

2024-03-22 13:23 UTC, Vanessa-Kris commented on src/App.css
> +
@PromiseFru  done.

2024-03-22 13:24 UTC, PromiseFru commented
Thank you, @Vanessa-Kris! We could make the table responsive for mobile view and consider adding a back button to the test display page. 

![image](https://github.com/smswithoutborders/gateway-client-reliability-dashboard/assets/33162641/e34eb1a4-0469-40f4-8443-2340ba76a03d)

![image](https://github.com/smswithoutborders/gateway-client-reliability-dashboard/assets/33162641/a70a3377-9b86-49b9-b55a-a9cd8eba7a9c)

2024-03-22 13:39 UTC, PromiseFru approved these changes
LGTM thank you @Vanessa-Kris!

2024-03-22 13:42 UTC, Vanessa-Kris commented
Thank you! @PromiseFru  I've also added the back button

2024-03-22 13:47 UTC, merged